policies:
product_name:
product_version:
ignored_patterns:
  - '.git/*'
  - 'scan-results/files-sbom-cyclonedx.json'
  - 'react-frontend.git/scan-results/syft.json'
scan_max_file_size:
attribution_template:
ignored_vulnerabilities:
ignored_dependency_scopes: