policies:
product_name:
product_version:
ignored_patterns:
  - 'react-frontend.git/.git/*'
  - 'react-frontend.git/scan-results/*'
scan_max_file_size:
attribution_template:
ignored_vulnerabilities:
ignored_dependency_scopes: