name: Scancode.io
on:
  push:
    tags:        
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs: 
  use-scancode-action:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: "${{ github.event.repository.name }}-${{ github.ref_name }}"
    steps:
      - uses: actions/checkout@v4
        with:
          path: scancode-inputs
      - uses: aboutcode-org/scancode-action@beta
        with:
          pipelines: "resolve_dependencies:StaticResolver"
          output-formats: "json xlsx spdx cyclonedx attribution"
          project-name: "${{ env.PROJECT_NAME }}"