name: Build and Push Docker Image + Generate SBOM

on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract commit SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image (latest + commit hash)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            securapoint/react-frontend:latest
            securapoint/react-frontend:${{ steps.vars.outputs.sha_short }}

      - name: Install Syft and generate SBOM
        uses: anchore/sbom-action@v0
        with:
          image: securapoint/react-frontend:${{ steps.vars.outputs.sha_short }}
          format: spdx-json
          output-file: sbom/syft-sbom-${{ steps.vars.outputs.sha_short }}.spdx.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: syft-sbom
          path: sbom/syft-sbom-${{ steps.vars.outputs.sha_short }}.spdx.json

      - name: Generate SBOM and submit to GitHub dependency graph
        uses: anchore/sbom-action@v0.15.3
        with:
          image: securapoint/react-frontend:${{ steps.vars.outputs.sha_short }}
          output-format: github