name: Build and Push Docker Image + Generate SBOM

on:
  push:
    branches: [main]

jobs:
  build-and-analyse:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract commit SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      # QEMU for Cross-Builds (ARM <-> AMD)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push multi-arch image (latest + commit hash)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            securapoint/react-frontend:latest
            securapoint/react-frontend:${{ steps.vars.outputs.sha_short }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false  # optional, makes sure there are no SBOM/Attestation conflicts with future steps

      - name: Generate image SBOM and upload artifact
        uses: anchore/sbom-action@v0
        with:
          image: securapoint/react-frontend:${{ steps.vars.outputs.sha_short }}
          format: cyclonedx-json
          output-file: syft-sbom-image-${{ steps.vars.outputs.sha_short }}.cyclonedx.json
          config: .syft.yaml

      - name: Generate path SBOM and upload artifact
        uses: anchore/sbom-action@v0
        with:
          path: ./
          format: cyclonedx-json
          output-file: syft-sbom-file-${{ steps.vars.outputs.sha_short }}.cyclonedx.json
          config: .syft.yaml